UPDATE produtos SET preco = 17.99 WHERE nome = 'Caderno Universitario';
UPDATE produtos SET categoria = 'Escritório' WHERE nome = 'Caneta Esferografica Azul';
UPDATE produtos SET nome = 'Bloco Adesivo Colorido' WHERE nome = 'Bloco de Notas Adesivas';
ALTER TABLE produtos ADD descricao TEXT;
UPDATE produtos SET descricao = 'Conjunto de lápis coloridos para uso artístico e escolar' WHERE nome = 'Lapis de Cor 12 Cores';
UPDATE produtos SET preco = 2.00 WHERE nome = 'Apontador de Lapis';
UPDATE produtos SET preco = 10.00 WHERE nome = 'Grampeador Pequeno';
UPDATE produtos SET categoria = 'Material Escolar' WHERE nome = 'Marcador de Texto Amarelo';
UPDATE produtos SET nome = 'Tesoura de Segurança' WHERE nome = 'Tesoura Escolar';
UPDATE produtos SET preco = 5.00 WHERE nome = 'Cola Branca 90g';
UPDATE produtos SET nome = 'Pasta Organizadora' WHERE nome = 'Pasta Sanfonada';
UPDATE produtos SET preco = 16.00 WHERE nome = 'Papel Sulfite A4';
UPDATE produtos SET descricao = 'Adesivos coloridos e decorativos para personalizar cadernos e álbuns' WHERE nome = 'Adesivos Decorativos';
UPDATE produtos SET categoria = 'Papelaria Criativa' WHERE nome = 'Caderno de Desenho';
UPDATE produtos SET preco = 8.00 WHERE nome = 'Canetinha Hidrocor';
UPDATE produtos SET nome = 'Lapis HB' WHERE nome = 'Lapis Grafite HB';
UPDATE produtos SET categoria = 'Agenda e Planejamento' WHERE nome = 'Bloco de Anotacoes';
UPDATE produtos SET preco = 39.00 WHERE nome = 'Fichário Universitário';
UPDATE produtos SET descricao = 'Carimbo automático com data ajustável' WHERE nome = 'Carimbo de Data';
UPDATE produtos SET categoria = 'Escritório' WHERE nome = 'Etiquetas Adesivas';
UPDATE produtos SET preco = 8.00 WHERE nome = 'Pasta com Elastico';
UPDATE produtos SET preco = 20.00 WHERE nome = 'Planner Semanal';
UPDATE produtos SET nome = 'Notas Autoadesivas' WHERE nome = 'Bloco de Recados';
UPDATE produtos SET preco = 25.00 WHERE nome = 'Calculadora Simples';
UPDATE produtos SET descricao = 'Agenda anual de 2024 com capa dura' WHERE nome = 'Agenda 2024';
UPDATE produtos SET preco = 6.00 WHERE nome = 'Marcador de Quadro Branco';
UPDATE produtos SET nome = 'Papel Fotografico Glossy' WHERE nome = 'Papel Fotografico A4';
UPDATE produtos SET preco = 3.00 WHERE nome = 'Caneta Gel Preta';
UPDATE produtos SET preco = 25.00 WHERE nome = 'Caixa Organizadora Media';
UPDATE produtos SET categoria = 'Linguagem e Alfabetização' WHERE nome = 'Caderno de Linguagem';
UPDATE produtos SET nome = 'Pen Drive USB 32GB' WHERE nome = 'Pen Drive 32GB';
UPDATE produtos SET categoria = 'Artesanato e Personalização' WHERE nome = 'Carimbo Personalizado';
UPDATE produtos SET preco = 15.90 WHERE nome = 'Caderno de Receitas';
UPDATE produtos SET preco = 80.00 WHERE nome = 'Calculadora Financeira';
UPDATE produtos SET nome = 'Pasta com Ziper' WHERE nome = 'Pasta de Zíper Plástica';
UPDATE produtos SET preco = 45.00 WHERE nome = 'Quadro Branco 60x40cm';
UPDATE produtos SET descricao = 'Caneta para desenho técnico com ponta fina de 0.3mm' WHERE nome = 'Caneta Tecnica 0.3mm';
UPDATE produtos SET preco = 10.50 WHERE nome = 'Estilete de Precisao';
UPDATE produtos SET nome = 'Tesoura de Corte Precisao' WHERE nome = 'Tesoura de Precisao';
UPDATE produtos SET categoria = 'Escritório' WHERE nome = 'Bloco de Folhas A3';
UPDATE produtos SET preco = 10.00 WHERE nome = 'Caderno de Anotacoes';
UPDATE produtos SET nome = 'Pen Drive USB 64GB' WHERE nome = 'Pen Drive 64GB';
UPDATE produtos SET descricao = 'Clips coloridos para papel, pacote com 50 unidades' WHERE nome = 'Caixa de Clips Coloridos';
UPDATE produtos SET categoria = 'Ferramentas e Acessórios' WHERE nome = 'Grampeador Grande';
UPDATE produtos SET preco = 14.00 WHERE nome = 'Caderno de Notas';
UPDATE produtos SET preco = 34.00 WHERE nome = 'Caixa Organizadora Grande';
UPDATE produtos SET preco = 20.00 WHERE nome = 'Lapis de Cor 24 Cores';
UPDATE produtos SET categoria = 'Escritório' WHERE nome = 'Caneta Rollerball';
UPDATE produtos SET preco = 20.00 WHERE nome = 'Caneta Tecnica 0.5mm';
UPDATE produtos SET preco = 1.50 WHERE nome = 'Lapis Preto HB';
UPDATE produtos SET nome = 'Apagador de Quadro' WHERE nome = 'Apagador para Quadro Branco';
UPDATE produtos SET categoria = 'Planejamento' WHERE nome = 'Planner Mensal';
UPDATE produtos SET preco = 7.00 WHERE nome = 'Caderno de Notas Pequeno';
UPDATE produtos SET descricao = 'Caneta em gel com tinta azul, ideal para escrita suave' WHERE nome = 'Caneta Gel Azul';
UPDATE produtos SET categoria = 'Escritório' WHERE nome = 'Caneta de Tinta Permanente';
UPDATE produtos SET preco = 35.00 WHERE nome = 'Caixa de Lapis de Cor 36 Cores';
UPDATE produtos SET nome = 'Pasta de Arquivo A4' WHERE nome = 'Pasta Fichario A4';
UPDATE produtos SET descricao = 'Caderno com capa dura, resistente para uso diário' WHERE nome = 'Caderno com Capa Dura';
UPDATE produtos SET categoria = 'Material Escolar' WHERE nome = 'Caneta Corretiva';
UPDATE produtos SET preco = 15.00 WHERE nome = 'Kit de Marcadores de Quadro Branco';




