UPDATE produtos SET preco = preco * 1.1 WHERE categoria = 'Material Escolar'; 
UPDATE produtos SET preco = preco * 1.05 WHERE categoria = 'Escritorio';
UPDATE produtos SET preco = preco * 1.2 WHERE categoria = 'Organizacao';
UPDATE produtos SET preco = preco * 1.15 WHERE categoria = 'Tecnologia e Acessorios';
UPDATE produtos SET preco = preco * 1.1 WHERE categoria = 'Embalagem e Presentes';
UPDATE produtos SET preco = preco * 1.05 WHERE categoria = 'Brinquedos e Lembrancinhas';
UPDATE produtos SET preco = preco * 1.1 WHERE categoria = 'Papeis';
UPDATE produtos SET preco = preco * 1.2 WHERE categoria = 'Papelaria Criativa';
UPDATE produtos SET preco = preco * 1.15 WHERE categoria = 'Material para Desenho';
UPDATE produtos SET preco = preco * 1.1 WHERE categoria = 'Material de Escritório';
UPDATE produtos SET preco = preco * 1.05 WHERE categoria = 'Ferramentas de Escritório';
UPDATE produtos SET nome = 'Novo Material Escolar' WHERE preco > 50.00;
UPDATE produtos SET nome = 'Material Acessível' WHERE preco < 5.00;
UPDATE produtos SET preco = 18.00 WHERE preco BETWEEN 10.00 AND 20.00;
UPDATE produtos SET nome = 'Caneta Azul' WHERE nome LIKE '%caneta%';
UPDATE produtos SET nome = 'Caderno Espiral' WHERE nome LIKE '%caderno%';
UPDATE produtos SET nome = 'Papel A4' WHERE nome LIKE '%papel%';
UPDATE produtos SET nome = 'Fita Adesiva' WHERE nome LIKE '%fita%';
UPDATE produtos SET nome = 'Cola Branca' WHERE nome LIKE '%cola%';
UPDATE produtos SET preco = 20.00 WHERE preco >= 15.00;
UPDATE produtos SET preco = 25.00 WHERE preco <= 30.00;
UPDATE produtos SET nome = 'Caderno 1 Materia' WHERE nome IN ('Caderno 1 Materia', 'Caderno 10 Materias');
UPDATE produtos SET preco = 12.00 WHERE id IN (1, 2, 3);
UPDATE produtos SET nome = 'Brinquedo Educativo' WHERE categoria = 'Brinquedos e Lembrancinhas' AND preco < 15.00;
UPDATE produtos SET preco = 22.00 WHERE categoria = 'Material Escolar' AND preco > 20.00;
UPDATE produtos SET nome = 'Caixa de Presente' WHERE categoria = 'Embalagem e Presentes' AND nome LIKE '%caixa%';
UPDATE produtos SET nome = 'Produto Sem Letra A' WHERE nome NOT LIKE '%a%';
UPDATE produtos SET preco = 8.00 WHERE categoria = 'Escritorio' AND preco BETWEEN 5.00 AND 10.00;
UPDATE produtos SET preco = 35.00 WHERE categoria = 'Tecnologia e Acessorios' AND preco > 30.00;
UPDATE produtos SET nome = 'Adesivo Colorido' WHERE categoria = 'Papelaria Criativa' AND nome LIKE '%adesivo%';
UPDATE produtos SET preco = 15.00 WHERE categoria = 'Material para Desenho' AND preco < 20.00;
UPDATE produtos SET nome = 'Papel Colorido' WHERE categoria = 'Papeis' AND nome IN ('Papel A4', 'Papel Colorido');
UPDATE produtos SET preco = 45.00 WHERE preco > 40.00;
UPDATE produtos SET preco = 20.00 WHERE preco < 25.00;
UPDATE produtos SET nome = 'Produto Atualizado' WHERE id >= 100;
UPDATE produtos SET nome = 'Organizador de Mesa' WHERE categoria = 'Organizacao' AND nome LIKE '%organizador%';
UPDATE produtos SET nome = 'Caderno Novo' WHERE nome = 'Caderno 10 Materias' OR nome = 'Caderno 1 Materia';
UPDATE produtos SET preco = 16.00 WHERE categoria = 'Brinquedos e Lembrancinhas' AND preco > 10.00;
UPDATE produtos SET preco = 9.00 WHERE categoria = 'Papelaria Criativa' AND preco <= 12.00;
UPDATE produtos SET nome = 'Grafite 2B' WHERE categoria = 'Material Escolar' AND nome LIKE '%grafite%';
UPDATE produtos SET nome = 'Mouse Sem Fio' WHERE categoria = 'Tecnologia e Acessorios' AND nome LIKE '%mouse%';
UPDATE produtos SET nome = 'Lápis Preto' WHERE nome LIKE '%lapis%';
UPDATE produtos SET nome = 'Lápis Colorido' WHERE nome LIKE '%lapis%';
UPDATE produtos SET nome = 'Caderno Universitário' WHERE categoria = 'Material Escolar' AND nome LIKE '%caderno%';
UPDATE produtos SET preco = 12.00 WHERE categoria = 'Embalagem e Presentes' AND preco < 20.00;
UPDATE produtos SET nome = 'Grampeador de Mesa' WHERE categoria = 'Material de Escritório' AND nome NOT LIKE '%grampeador%';
UPDATE produtos SET preco = 11.00 WHERE categoria = 'Organizacao' AND preco BETWEEN 5.00 AND 15.00;
UPDATE produtos SET nome = 'Caneta Vermelha' WHERE categoria = 'Escritorio' AND nome LIKE '%caneta%';
UPDATE produtos SET nome = 'Produto 10' WHERE id IN (10, 20, 30);
UPDATE produtos SET preco = 55.00 WHERE preco >= 50.00;
UPDATE produtos SET nome = 'Pincel Aquarela' WHERE categoria = 'Material para Desenho' AND nome NOT LIKE '%pincel%';
UPDATE produtos SET nome = 'Caderno Personalizado' WHERE nome LIKE '%caderno%';
UPDATE produtos SET preco = 5.00 WHERE categoria = 'Papeis' AND preco < 10.00;
UPDATE produtos SET preco = 30.00 WHERE categoria = 'Tecnologia e Acessorios' AND preco > 25.00;
UPDATE produtos SET nome = 'Apontador Elétrico' WHERE categoria = 'Material Escolar' AND nome LIKE '%apontador%';
UPDATE produtos SET nome = 'Brinquedo de Montar' WHERE categoria = 'Brinquedos e Lembrancinhas' AND preco >= 15.00;
UPDATE produtos SET preco = 6.00 WHERE categoria = 'Papelaria Criativa' AND preco < 7.00;
UPDATE produtos SET nome = 'Sacola de Papel' WHERE categoria = 'Embalagem e Presentes' AND nome LIKE '%sacola%';
UPDATE produtos SET nome = 'Caneta Para Quadro' WHERE categoria = 'Escritorio' AND nome LIKE '%caneta%';
UPDATE produtos SET preco = preco * 1.1 WHERE categoria = 'Material Escolar' AND preco < 20.00; 
