DELETE FROM produtos WHERE nome = 'Cola Branca 90g';
DELETE FROM produtos WHERE categoria = 'Material Escolar' AND preco > 30.00;
DELETE FROM produtos WHERE id BETWEEN 15 AND 20;
DELETE FROM produtos WHERE nome LIKE '%Papel%';
DELETE FROM produtos WHERE categoria = 'Escritorio' AND preco < 25.00;
DELETE FROM produtos WHERE id = 200;
DELETE FROM produtos WHERE preco > 45.00;
DELETE FROM produtos WHERE nome = 'Pasta Sanfonada';
DELETE FROM produtos WHERE categoria = 'Arte e Desenho' AND preco > 25.00;
DELETE FROM produtos WHERE preco BETWEEN 20.00 AND 30.00;
DELETE FROM produtos WHERE nome LIKE '%Lapis%';
DELETE FROM produtos WHERE categoria = 'Papelaria Criativa' AND preco < 15.00;
DELETE FROM produtos WHERE id BETWEEN 20 AND 25;
DELETE FROM produtos WHERE preco < 15.00;
DELETE FROM produtos WHERE nome = 'Marcador de Texto Amarelo';
DELETE FROM produtos WHERE categoria = 'Material Escolar' AND preco > 40.00;
DELETE FROM produtos WHERE id > 190;
DELETE FROM produtos WHERE categoria LIKE '%O%';
DELETE FROM produtos WHERE categoria = 'Escritorio' AND preco > 35.0;
DELETE FROM produtos WHERE nome LIKE '%F%';
DELETE FROM produtos WHERE preco > 50.00;
DELETE FROM produtos WHERE nome = 'Tinta Guache 6 Cores';
DELETE FROM produtos WHERE categoria = 'Arte e Desenho' AND preco < 30.00;
DELETE FROM produtos WHERE id BETWEEN 25 AND 30;
DELETE FROM produtos WHERE nome LIKE '%Papel%';
DELETE FROM produtos WHERE categoria = 'Papelaria Criativa' AND preco > 20.00;
DELETE FROM produtos WHERE id = 25;
DELETE FROM produtos WHERE preco < 20.00;
DELETE FROM produtos WHERE nome = 'Lapis Grafite HB';
DELETE FROM produtos WHERE categoria = 'Material Escolar' AND preco > 45.00;
